# Nama workflow ini akan muncul di tab "Actions" GitHub Anda
name: Generate Snake Animation

# Tentukan kapan workflow ini akan berjalan
on:
  # Jalankan setiap hari pada pukul 00:00 UTC (Anda bisa sesuaikan jadwalnya)
  schedule:
    - cron: "0 0 * * *"
  # Izinkan pemicuan manual dari tab "Actions"
  workflow_dispatch:

jobs:
  build:
    # Jalankan di runner Ubuntu terbaru
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout repositori Anda
      - name: Checkout Repositori
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Langkah 2: Buat Animasi Ular
      - name: Buat Animasi Ular GitHub
        uses: Platane/snk@v2
        with:
          # --- KOREKSI INI: Ganti ke username GitHub Anda yang sebenarnya ---
          github_user_name: rhyghtnn # <--- HARUSNYA 'rhyghtnn'
          # Lokasi output file GIF di dalam runner
          gif_out_path: dist/github-snake.gif

      # Langkah 3: Commit dan Push GIF yang Dihasilkan ke Repositori
      - name: Commit dan Push GIF Ular
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-snake.gif
          git commit -m "feat: perbarui animasi ular github" || echo "Tidak ada perubahan untuk di-commit"
          git push

      # Langkah 4: (Opsional) Unggah GIF sebagai Artefak
      - name: Unggah Animasi Ular sebagai Artefak
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/github-snake.gif
