name: Generate Snake Animation

on:
  schedule:
    - cron: '0 0 * * *'  # Menjalankan setiap hari pada pukul 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake Game
        uses: Platane/snk@v2
        with:
          github_user_name: rayhantuanto  # Ganti dengan nama pengguna GitHub Anda
          gif_out_path: dist/github-snake.gif

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/github-snake.gif